# ----------------------------------------------
# Settings
# ----------------------------------------------

/control/verbose 2
/material/verbose 2
/run/verbose 2
/event/verbose 0
/tracking/verbose 0

# ----------------------------------------------
# CRY Settings
# ----------------------------------------------

/control/execute Cry.mac

# ----------------------------------------------
# DM Settings
# ----------------------------------------------

/scatter/DM 1.0e-02 GeV 1.0e-05 cm2
#/scatter/DM 1.0e-01 GeV 1.0e-04 cm2
#/scatter/DM 1.0e+00 GeV 1.0e-03 cm2
#/scatter/DM 1.0e+01 GeV 1.0e-02 cm2
#/scatter/DM 1.0e+02 GeV 1.0e-01 cm2

# ----------------------------------------------
# run
# ----------------------------------------------

/run/initialize
/rlt/SetFileName root_file/CryMu.root
/run/printProgress 1000
/run/beamOn 100000
