# ----------------------------------------------
# Settings
# ----------------------------------------------

/control/verbose 2
/gps/verbose 0
/material/verbose 2
/run/verbose 2
/event/verbose 0
/tracking/verbose 0

# ----------------------------------------------
# CLFV Settings
# ----------------------------------------------

/scatter/mupTargetEnToLL 13 ../clfv/data/muemumu_ki_2.200000000000000011e-01.root 1000.0
#/run/setCut 0.7 mm

# ----------------------------------------------
# General Particle Source (GPS) Settings
# ----------------------------------------------

/gps/particle mu+
/gps/direction 0.0 0.0 1.0
/gps/totalEnergy 50 GeV

# ----------------------------------------------
# run
# ----------------------------------------------

/run/initialize
/rlt/SetFileName root_file/mup_50GeV.root
/run/printProgress 1000
/run/beamOn 100000
