# ----------------------------------------------
# Settings
# ----------------------------------------------

/control/verbose 2
/gps/verbose 0
/material/verbose 2
/run/verbose 2
/event/verbose 0
/tracking/verbose 0

# ----------------------------------------------
# CLFV Settings
# ----------------------------------------------

/scatter/mupTargetEnToLL 1000.0 mup_energy_10.0GeV_Zp_0.003000GeV.txt
#/run/setCut 0.7 mm

# ----------------------------------------------
# General Particle Source (GPS) Settings
# ----------------------------------------------

/gps/particle mu+
/gps/direction 0.0 0.0 1.0
/gps/totalEnergy 10.0 GeV

# ----------------------------------------------
# run
# ----------------------------------------------

/run/initialize
/rlt/SetFileName root_file/mup_10.0GeV_Zp_0.003000GeV_mue_x1e+03.root
/run/printProgress 1000
/run/beamOn 10000
