# Schema
schema: volume_schema.yaml

---

world_major_gap:
  hidden: hidden
  alternative: alternative
  solid: box
  x: &world_x 200 mm
  y: &world_y 200 mm
  z: 500 mm  # [NOTE] mid-to-mid
  mid_to_mid: mid_to_mid
  material: &world_material G4_AIR

world_minor_gap:
  hidden: hidden
  alternative: alternative
  solid: box
  x: *world_x
  y: *world_y
  z: 250 mm  # [NOTE] mid-to-mid
  mid_to_mid: mid_to_mid
  material: *world_material

world:
  alternative: alternative
  solid: bottom_up
  components:
    - mwdc_up_detector
    - world_minor_gap
    - mwdc_up_detector
    - world_major_gap
    - mwdc_down_detector
    - world_minor_gap
    - mwdc_down_detector
  padding: 20%
  material: *world_material

---

# Comments
