# Schema
schema: volume_schema.yaml

---

target:
  color: gray
  solid: box
  x: 120 mm
  y: 120 mm
  z: 30 mm
  material: G4_Pb

world_major_gap:
  hidden: hidden
  solid: box
  x: &rpc_x 430 mm
  y: &rpc_y 430 mm
  z: 455 mm
  material: &world_material rpc_air

world_minor_gap_up:
  hidden: hidden
  solid: box
  x: *rpc_x
  y: *rpc_y
  z: &rpc_minor_gap_z 155 mm
  material: *world_material

world_minor_gap_down:
  hidden: hidden
  solid: bottom_up
  components: [target]
  x: *rpc_x
  y: *rpc_y
  z: *rpc_minor_gap_z
  material: *world_material

world:
  hidden: hidden
  solid: bottom_up
  components:
    - rpc
    - world_minor_gap_down
    - rpc
    - world_major_gap
    - rpc
    - world_minor_gap_up
    - rpc
  padding: 20%
  material: *world_material

---

# Comments
materials:
  - rpc_air
external:
  - rpc
