# Schema
schema: volume_schema.yaml

---

target:
  color: gray
  solid: box
  x: 120 mm
  y: 120 mm
  z: 30 mm
  material: rpc_glass

world_major_gap:
  hidden: hidden
  solid: bottom_up
  components: [target]
  x: &rpc_x 430 mm
  y: &rpc_y 430 mm
  z: 455 mm
  offset: [0, 0, 62.5 mm]
  material: &world_material rpc_air

---

# Comments
materials:
  - G4_Al
  - rpc_air
external:
  - rpc
