# Schema
schema: volume_schema.yaml

---

world_major_gap:
  hidden: hidden
  solid: box
  x: &rpc_x 430 mm
  y: &rpc_y 430 mm
  z: 455 mm
  material: &world_material rpc_air
  
world_minor_gap:
  hidden: hidden
  solid: box
  x: *rpc_x
  y: *rpc_y
  z: 155 mm
  material: *world_material

world:
  hidden: hidden
  solid: bottom_up
  components:
    - rpc
    - world_minor_gap
    - rpc
    - world_major_gap
    - rpc
    - world_minor_gap
    - rpc
  padding: 20%
  material: *world_material

---

# Comments
materials:
  - rpc_air
external:
  - rpc
