# Schema
schema: volume_schema.yaml
---

mwdc_down_film:
  solid: box
  x: &mwdc_down_film_x 20 * cm
  y: &mwdc_down_film_y 20 * cm
  z: 13 * um
  material: mwdc_film

mwdc_down_gas_film_to_wires:
  solid: box
  x: *mwdc_down_film_x
  y: *mwdc_down_film_y
  z: 22 * mm
  mid_to_mid: mid_to_mid
  material: mwdc_gas

mwdc_down_gas_wires_to_film:
  solid: box
  x: *mwdc_down_film_x
  y: *mwdc_down_film_y
  z: 21 * mm
  mid_to_mid: mid_to_mid
  material: mwdc_gas

mwdc_down_gas_wires:
  solid: box
  x: *mwdc_down_film_x
  y: *mwdc_down_film_y
  z: 5 * mm
  mid_to_mid: mid_to_mid
  material: mwdc_gas

mwdc_down_field_wires:
  solid: box
  x: &mwdc_down_sensitive_x 16 * cm
  y: &mwdc_down_sensitive_y 16 * cm
  z: 75 * um
  material: mwdc_down_field_wires

mwdc_down_signal_wires:
  solid: box
  x: *mwdc_down_sensitive_x
  y: *mwdc_down_sensitive_y
  z: 20 * um
  material: mwdc_down_signal_wires

mwdc_down_detector:
  solid: bottom_up
  components:
    - mwdc_down_film
    - mwdc_down_gas_film_to_wires

    - mwdc_down_field_wires   # 0
    - mwdc_down_gas_wires
    - mwdc_down_signal_wires  # 1
    - mwdc_down_gas_wires
    - mwdc_down_field_wires   # 2
    - mwdc_down_gas_wires
    - mwdc_down_signal_wires  # 3
    - mwdc_down_gas_wires
    - mwdc_down_field_wires   # 4
    - mwdc_down_gas_wires
    - mwdc_down_field_wires   # 5
    - mwdc_down_gas_wires
    - mwdc_down_signal_wires  # 6
    - mwdc_down_gas_wires
    - mwdc_down_field_wires   # 7
    - mwdc_down_gas_wires
    - mwdc_down_signal_wires  # 8
    - mwdc_down_gas_wires
    - mwdc_down_field_wires   # 9

    - mwdc_down_gas_wires_to_film
    - mwdc_down_film

---

# Comments
