# Schema
name:  # unique LV name to create
  alternative: # optional, disabling override
  solid: box  # G4Box
  solid: bottom_up  # G4Box
  components:  # significant when solid=bottom_up
  padding:  # significant when solid=bottom_up, optional, excluding x, y, z
  x:  # optional
  y:  # optional
  z:  # optional
  material:  # argument for G4Material::GetMaterial

---

rpc_insulating_film:
  solid: box
  x: 300 mm
  y: 300 mm
  z: 0.1 mm
  material: rpc_pet
rpc_electrode:
  solid: box
  x: 203 mm
  y: 203 mm
  z: 0.2 mm
  material: G4_GRAPHITE
rpc_glass:
  solid: box
  x: 300 mm
  y: 300 mm
  z: 2.7 mm
  material: rpc_glass
rpc_gas:
  solid: box
  x: 420 mm
  y: 420 mm
  z: 2 mm
  material: rpc_gas
rpc_screw_gap:
  solid: box
  x: 420 mm
  y: 420 mm
  z: 6 mm
  material: rpc_gas
x_readout_board:
  alternative: alternative
  solid: box
  x: 300 mm
  y: 300 mm
  z: 1.6 mm
  material: G4_Cu
t_readout_board:
  alternative: alternative
  solid: box
  x: 300 mm
  y: 300 mm
  z: 1.6 mm
  material: G4_Cu
y_readout_board:
  alternative: alternative
  solid: box
  x: 300 mm
  y: 300 mm
  z: 1.6 mm
  material: G4_Cu

rpc_electrode_pair:
  solid: bottom_up
  components:
    - rpc_insulating_film
    - rpc_electrode
    - rpc_glass
    - rpc_gas
    - rpc_glass
    - rpc_electrode
    - rpc_insulating_film
  material: rpc_gas

rpc_mainbody:
  solid: bottom_up
  components:
    - x_readout_board  # external
    - rpc_electrode_pair
    - rpc_gas
    - t_readout_board  # external
    - rpc_gas
    - rpc_electrode_pair
    - y_readout_board  # external
  material: rpc_gas

rpc_content:
  solid: bottom_up
  components:
    - rpc_screw_gap
    - rpc_mainbody
    - rpc_gas
  material: rpc_gas

rpc:
  solid: bottom_up
  components: [rpc_content]
  padding: 5 mm
  material: G4_Al

---

# Comments
materials:
  - G4_Al
  - G4_GRAPHITE
  - rpc_gas
  - rpc_glass
  - rpc_pet
external:
  - x_readout_board
  - t_readout_board
  - y_readout_board
