# Schema
schema: volume_schema.yaml

---

rpc_insulating_film:
  solid: box
  x: &rpc_mainbody_x 300 mm
  y: &rpc_mainbody_y 300 mm
  z: 0.1 mm
  material: rpc_insulating_film

rpc_electrode:
  solid: box
  x: 203 mm
  y: 203 mm
  z: 0.2 mm
  material: rpc_electrode

rpc_glass:
  solid: box
  x: *rpc_mainbody_x
  y: *rpc_mainbody_y
  z: 2.7 mm
  material: rpc_glass

rpc_gas:
  solid: box
  x: &rpc_content_x 420 mm
  y: &rpc_content_y 420 mm
  z: 2 mm
  material: rpc_gas

rpc_screw_gap:
  solid: box
  x: *rpc_content_x
  y: *rpc_content_y
  z: 6 mm
  material: rpc_gas

rpc_x_readout_board: &rpc_readout_board
  alternative: alternative
  solid: box
  x: *rpc_mainbody_x
  y: *rpc_mainbody_y
  z: 1.6 mm
  material: rpc_fr4

rpc_t_readout_board: *rpc_readout_board
rpc_y_readout_board: *rpc_readout_board

rpc_electrode_pair:
  solid: bottom_up
  components:
    - rpc_insulating_film
    - rpc_electrode
    - rpc_glass
    - rpc_gas
    - rpc_glass
    - rpc_electrode
    - rpc_insulating_film
  material: rpc_gas

rpc_mainbody:
  solid: bottom_up
  components:
    - rpc_x_readout_board  # external
    - rpc_electrode_pair
    - rpc_gas
    - rpc_t_readout_board  # external
    - rpc_gas
    - rpc_electrode_pair
    - rpc_y_readout_board  # external
  material: rpc_gas

rpc_content:
  solid: bottom_up
  components:
    - rpc_screw_gap
    - rpc_mainbody
    - rpc_gas
  z: 35 mm
  material: rpc_gas

rpc:
  solid: bottom_up
  components: [rpc_content]
  padding: 5 mm
  material: rpc_shell

---

# Comments
materials:
  - rpc_electrode
  - rpc_fr4
  - rpc_gas
  - rpc_glass
  - rpc_insulating_film
  - rpc_shell
external:
  - rpc_x_readout_board
  - rpc_t_readout_board
  - rpc_y_readout_board
