# Schema
schema: schema.yaml

---

rpc_readout_plate:
  solid: box
  x: &rpc_readout_board_x 300 mm
  y: &rpc_readout_board_y 300 mm
  z: 1.4 mm
  material: rpc_fr4

rpc_readout_cu:
  solid: box
  x: *rpc_readout_board_x
  y: *rpc_readout_board_y
  z: 0.1 mm
  material: G4_Cu

rpc_readout_bar:
  solid: box
  x: 2.0 mm
  y: &rpc_readout_bar_y 200 mm
  z: &rpc_readout_bar_z 0.1 mm
  material: G4_Cu

rpc_readout_gas:
  solid: box
  x: 0.27 mm
  y: *rpc_readout_bar_y
  z: *rpc_readout_bar_z
  material: rpc_gas

rpc_readout_bars:
  solid: left_right
  components:
    - rpc_readout_gas
    - rpc_readout_bar
    - rpc_readout_gas
  duplicate: 80
  material: rpc_gas

rpc_readout_board:
  solid: bottom_up
  components:
    - rpc_readout_plate
    - rpc_readout_cu
    - rpc_readout_bars
  material: rpc_gas

rpc_x_readout_board:
  solid: rotation
  components: [rpc_readout_board]

rpc_y_readout_board:
  solid: rotation
  components: [rpc_readout_board, [z, 90 deg]]

---

# Comments
materials:
  - G4_Cu
  - rpc_fr4
  - rpc_gas
