# Schema
schema: volume_schema.yaml

---

silicon_strip:
  solid: box
  x: &silicon_strip_x 0.1 mm  # width
  y: &silicon_strip_y 100 mm  # length
  z: &silicon_strip_z 320 um  # thickness
  material: silicon_strip
  step_limit: 32 um           # [NOTE] 0.1 * *silicon_strip_z
  color: red
  alpha: 0.8

silicon_plane:
  solid: left_right
  components: [silicon_strip]
  duplicate: 1000
  material: silicon_air

silicon_plane_gap:
  solid: box
  x: *silicon_strip_x
  y: *silicon_strip_y
  z: 1.8 mm  # [NOTE] https://cds.cern.ch/record/2896293/files/SPSC-P-370.pdf 4.1.1
  material: silicon_air

silicon_module:
  solid: bottom_up
  components:
    - silicon_plane
    - silicon_plane_gap
    - silicon_plane
  material: silicon_air

silicon_module_x:
  hidden: hidden
  solid: rotation
  components: [silicon_module, [z, 0 deg]]

silicon_module_y:
  hidden: hidden
  solid: rotation
  components: [silicon_module, [z, 90 deg]]

silicon_module_u:
  hidden: hidden
  solid: rotation
  components: [silicon_module, [z, 45 deg]]

silicon_module_v:
  hidden: hidden
  solid: rotation
  components: [silicon_module, [z, 135 deg]]

silicon_module_gap:
  solid: box
  x: *silicon_strip_x
  y: *silicon_strip_y
  z: 1.8 mm  # [TODO] Consolidate this value.
  material: silicon_air

silicon_module_xy:
  solid: bottom_up
  components:
    - silicon_module_x
    - silicon_module_gap
    - silicon_module_y
  material: silicon_air

silicon_module_uv:
  solid: bottom_up
  components:
    - silicon_module_u
    - silicon_module_gap
    - silicon_module_v
  material: silicon_air

---

# Comments
