# Schema
schema: volume_schema.yaml

---

world_major_gap:
  alternative: alternative
  solid: box
  x: &silicon_x 100 mm
  y: &silicon_y 100 mm
  z: 500 mm  # [NOTE] mid-to-mid [TODO] Optimize this value.
  mid_to_mid: mid_to_mid
  material: &world_material silicon_air

world_minor_gap:
  alternative: alternative
  solid: box
  x: *silicon_x
  y: *silicon_y
  z: 200 mm  # [NOTE] mid-to-mid [TODO] Optimize this value.
  mid_to_mid: mid_to_mid
  material: *world_material

world:
  alternative: alternative
  solid: bottom_up
  components:
    - silicon_module_xy
    - world_minor_gap
    - silicon_module_uv
    - world_minor_gap
    - silicon_module_xy
    - world_major_gap
    - silicon_module_xy
    - world_minor_gap
    - silicon_module_uv
    - world_minor_gap
    - silicon_module_xy
  padding: 20%
  material: *world_material

---

# Comments
